#!/bin/bash

# Aliases
alias gcl='git clone'
alias ga='git add'
alias gall='git add .'
alias gaa='git add . --all'
alias g='git'
alias get='git'
alias gst='git status'
alias gs='git status --short'
alias gl='git pull'
alias gup='git fetch && git rebase'
alias gp='git push'
alias gpo='git push origin'
alias gd='git diff'
alias gdv='git diff -w "$@" | vim -R -'
alias gc='git commit -vam '
alias gca='git commit -v -am'
alias gci='git commit --interactive'
alias gb='git branch'
alias gba='git branch -a'
alias gbr='git branch -r'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias gco='git checkout'
alias gdel='git branch -d'
alias gll='git log --decorate --graph --pretty=oneline --abbrev-commit'
alias glg='git log --decorate --graph --pretty=oneline --abbrev-commit'

